import { useEffect, useRef, useState } from "react";
import type { KnowledgeCitation, KnowledgeProposal, KnowledgeValue } from "../../../ontology/src/knowledge-contracts.js";
import { investigationVocabulary } from "../../../ontology/src/knowledge-contracts.js";
import { PdfCoverageNotice } from "../evidence/PdfCoverageNotice.js";
import { locatorLabel } from "../evidence/evidence-location.js";
import { displayValue, suggestEntityMatches, knowledgeRequest, newKnowledgeId, sourceLabel, type ReviewProposal, type SharedKnowledge, type SourceContent, type SourceItem } from "./shared-ontology-adapter.js";

const button = "rounded border border-[var(--console-line-strong)] px-3 py-2 text-sm disabled:opacity-50";
const field = "min-w-0 max-w-full rounded border border-[var(--console-line)] bg-[var(--console-panel)] p-2";
const box = "min-w-0 space-y-3 rounded border border-[var(--console-line)] p-4";
type Command = Record<string, unknown> & { decisionId: string; expectedRevision: number };

export function SharedOntologyWorkspace() {
  const [workspace, setWorkspace] = useState<SharedKnowledge>();
  const [sources, setSources] = useState<SourceItem[]>([]);
  const [error, setError] = useState<string>();
  const [notice, setNotice] = useState<string>();
  const [busy, setBusy] = useState(false);
  const [pending, setPending] = useState<Command>();
  const [selected, setSelected] = useState<string[]>([]);
  const [rationale, setRationale] = useState("");
  const [inspectId, setInspectId] = useState("");
  const [edit, setEdit] = useState<ReviewProposal>();
  const [query, setQuery] = useState("");
  const [entityId, setEntityId] = useState("");
  const [relationshipFilter, setRelationshipFilter] = useState("");
  const alive = useRef(true);
  async function refresh() {
    const [knowledge, evidence] = await Promise.all([knowledgeRequest<SharedKnowledge>("/api/ontology/knowledge"), knowledgeRequest<{ items: SourceItem[] }>("/api/evidence/workspace")]);
    if (alive.current) { setWorkspace(knowledge); setSources(evidence.items); setSelected([]); }
  }
  useEffect(() => { alive.current = true; void refresh().catch(reason => setError(reason instanceof Error ? reason.message : "Knowledge unavailable.")); return () => { alive.current = false; }; }, []);
  async function commit(command: Command) {
    setBusy(true); setError(undefined); setNotice(undefined); setPending(command);
    try {
      await knowledgeRequest("/api/ontology/commands", command);
      setPending(undefined); await refresh(); setNotice("Decision saved. Current views and preserved history have been refreshed.");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Decision unavailable."); }
    finally { setBusy(false); }
  }
  const decide = (body: Record<string, unknown>) => workspace ? commit({ ...body, decisionId: newKnowledgeId("decision"), expectedRevision: workspace.revision }) : Promise.resolve();
  if (!workspace) return <section aria-label="Shared ontology" className={box}><h2>Shared ontology</h2><p role={error ? "alert" : "status"}>{error ?? "Loading shared knowledge…"}</p><button className={button} onClick={() => void refresh().catch(reason => setError(String(reason)))}>Refresh shared ontology</button></section>;
  const currentCase = workspace.cases.find(item => item.caseId === workspace.selectedCaseId);
  const memberships = workspace.memberships.filter(item => item.included && item.caseId === currentCase?.caseId);
  const member = (kind: string, id: string) => memberships.some(item => item.targetKind === kind && item.targetId === id);
  const caseProposals = workspace.proposals.filter(proposal => !currentCase || member("knowledge", proposal.assertionId) || proposal.evidence.some(ref => member("evidence", ref.evidenceId)) || workspace.entities.some(entity => member("entity", entity.entityId) && entity.assertionIds.includes(proposal.assertionId)));
  const dossier = workspace.entities.find(entity => entity.entityId === entityId);
  const visible = caseProposals.filter(proposal => !dossier || dossier.assertionIds.includes(proposal.assertionId) || proposal.subjectEntityId === dossier.entityId || proposal.objectEntityId === dossier.entityId || workspace.occurrences.some(occurrence => occurrence.assertionIds.includes(proposal.assertionId) && occurrence.participants.some(participant => participant.entityId === dossier.entityId)));
  const inspected = workspace.proposals.find(proposal => proposal.assertionId === inspectId);
  const relationships = visible.filter(proposal => proposal.kind === "relationship" && workspace.relationships.some(r => r.assertionIds.includes(proposal.assertionId)) && (!relationshipFilter || proposal.predicate === relationshipFilter));
  const occurrences = visible.filter(proposal => proposal.kind === "occurrence" && workspace.occurrences.some(o => o.assertionIds.includes(proposal.assertionId)));
  const caseNames = (ids: string[]) => ids.map(id => workspace.cases.find(item => item.caseId === id)?.title ?? id).join(", ") || "No case membership";
  const review = (ids: string[], action: string) => decide({ action: "review", reviews: ids.map(id => { const proposal = workspace.proposals.find(item => item.assertionId === id)!; return { assertionId: id, proposalEventId: proposal.proposalEventId, action, rationale }; }) });

  return <section aria-label="Shared ontology" className="space-y-5 text-[var(--paper-light)]">
    <div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-semibold">Shared investigation knowledge</h2><button className={button} disabled={busy} onClick={() => { setPending(undefined); setError(undefined); void refresh().catch(reason => setError(String(reason))); }}>Refresh shared ontology</button><span className="text-xs">Revision {workspace.revision}</span></div>
    <p>Cases share workspace identities and evidence. Proposals require human review. Manual curation works without an external provider.</p>
    {error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}
    {pending && !busy && <p>Review the error before proceeding. <button className={button} onClick={() => void commit(pending)}>Retry exact decision</button> uses the same decision identity and revision; refresh to abandon a stale decision.</p>}
    <fieldset disabled={busy} className="min-w-0 space-y-5">
      <section aria-label="Investigations" className={box}>
        <label className="flex flex-col gap-1">Current investigation<select className={field} value={workspace.selectedCaseId ?? ""} onChange={event => { setEntityId(""); void decide({ action: "selectCase", caseId: event.target.value || null }); }}><option value="">All cases · workspace view</option>{workspace.cases.map(item => <option key={item.caseId} value={item.caseId}>{item.title}</option>)}</select></label>
        {currentCase && <><h3 className="font-semibold">{currentCase.title}</h3><p>Question: {currentCase.question}</p><p>Scope: {currentCase.scope}</p><p>{currentCase.notes}</p></>}
        <details><summary>Create an investigation</summary><form aria-label="Create investigation" className="mt-3 grid gap-3" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); void decide({ action: "createCase", caseId: newKnowledgeId("case"), title: values.get("title"), question: values.get("question"), scope: values.get("scope"), notes: values.get("notes") ?? "" }); }}>
          <label className="flex flex-col gap-1">Investigation title<input name="title" className={field} required maxLength={1000} /></label>
          <label className="flex flex-col gap-1">Investigation question<textarea name="question" className={field} required maxLength={10000} /></label>
          <label className="flex flex-col gap-1">Investigation scope<textarea name="scope" className={field} required maxLength={10000} /></label>
          <label className="flex flex-col gap-1">Notes<textarea name="notes" className={field} maxLength={10000} /></label><button className={button}>Create investigation</button>
        </form></details>
        {currentCase && <>
          <details><summary>Evidence memberships</summary><p>Removing membership leaves shared evidence and knowledge intact.</p>{sources.map(source => <label key={source.evidenceId} className="flex items-start gap-2 py-2"><input type="checkbox" checked={member("evidence", source.evidenceId)} onChange={event => void decide({ action: "membership", caseId: currentCase.caseId, targetKind: "evidence", targetId: source.evidenceId, included: event.target.checked })} /><span className="break-words">{sourceLabel(source)}</span></label>)}</details>
          <details><summary>Case hypotheses</summary><p>Hypotheses are questions or explanations under investigation, separate from accepted assertions.</p>{workspace.hypotheses.filter(item => item.caseId === currentCase.caseId).map(item => <p key={item.hypothesisId}>{item.statement} · Supports: {item.supporting.join(", ") || "none"} · Contradicts: {item.contradicting.join(", ") || "none"}</p>)}<form className="space-y-2" onSubmit={event => { event.preventDefault(); const values = new FormData(event.currentTarget); void decide({ action: "hypothesis", caseId: currentCase.caseId, hypothesisId: newKnowledgeId("hypothesis"), statement: values.get("statement"), supporting: values.getAll("supporting"), contradicting: values.getAll("contradicting") }); }}><label className="flex flex-col gap-1">Hypothesis statement<textarea className={field} name="statement" required /></label><label className="flex flex-col gap-1">Hypothesis supporting knowledge<select className={field} name="supporting" multiple>{caseProposals.map(p => <option key={p.assertionId} value={p.assertionId}>{p.predicate}: {displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)} · {p.reviewState}</option>)}</select></label><label className="flex flex-col gap-1">Hypothesis contradicting knowledge<select className={field} name="contradicting" multiple>{caseProposals.map(p => <option key={p.assertionId} value={p.assertionId}>{p.predicate}: {displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)} · {p.reviewState}</option>)}</select></label><p>Hold Ctrl or Command to select several entries. Linking a proposal does not accept it as a fact.</p><button className={button}>Record case hypothesis</button></form></details>
        </>}
      </section>
      <ProposalComposer key={edit?.assertionId ?? "new"} workspace={workspace} sources={sources} edit={edit} onCancel={() => setEdit(undefined)} onPropose={async proposals => { await decide({ action: "propose", proposals }); }} />
      <section aria-label="Entity search and dossiers" className={box}>
        <h3 className="font-semibold">Entities across investigations</h3><label className="flex flex-col gap-1">Search entities<input className={field} value={query} onChange={event => setQuery(event.target.value)} placeholder="Name, identifier, or address" /></label>
        <button className={button} onClick={() => setEntityId("")}>Show all knowledge</button>
        <div className="flex flex-wrap gap-2">{workspace.entities.filter(entity => (!currentCase || entity.caseIds.includes(currentCase.caseId) || member("entity", entity.entityId)) && `${entity.canonicalLabel} ${entity.entityId} ${workspace.proposals.filter(p => p.subjectEntityId === entity.entityId).map(p => displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)).join(" ")}`.toLowerCase().includes(query.toLowerCase())).map(entity => <button className={button} key={entity.entityId} aria-pressed={entityId === entity.entityId} onClick={() => setEntityId(entity.entityId)}>{entity.canonicalLabel} · {entity.entityType}</button>)}</div>
        {dossier && <section aria-label="Entity dossier" className="space-y-2"><h4 className="font-semibold">{dossier.canonicalLabel}</h4><p className="break-all">{dossier.entityId} · {dossier.entityType}</p><p>Cases: {caseNames(dossier.caseIds)}</p><p>{dossier.evidenceIds.length} source records · {dossier.independentSourceCount} reviewed independent origins · Source independence {dossier.sourceIndependence}</p><p>Repeated mentions and case memberships do not add independent sources.</p>{workspace.cases.map(item => <label key={item.caseId} className="flex gap-2"><input type="checkbox" checked={workspace.memberships.some(m => m.included && m.targetKind === "entity" && m.targetId === dossier.entityId && m.caseId === item.caseId)} onChange={event => void decide({ action: "membership", caseId: item.caseId, targetKind: "entity", targetId: dossier.entityId, included: event.target.checked })} />Entity membership in {item.title}</label>)}</section>}
      </section>
      <section aria-label="Knowledge review" className={box}>
        <h3 className="font-semibold">Proposals and current knowledge</h3><p>Values are shown beside their source quotations. A model score is not a probability of truth. Unknown vocabulary remains proposed until replaced with a supported proposal.</p>
        <label className="flex flex-col gap-1">Decision rationale<textarea className={field} value={rationale} onChange={event => setRationale(event.target.value)} placeholder="Explain your review or correction" /></label>
        <div className="flex flex-wrap gap-2"><button className={button} disabled={!selected.length || !rationale.trim()} onClick={() => void review(selected, "accept")}>Accept selected proposals ({selected.length})</button><button className={button} disabled={!selected.length || !rationale.trim()} onClick={() => void review(selected, "reject")}>Reject selected proposals</button></div>
        {!visible.length && <p>No knowledge in this view. Add source memberships, make a manual proposal, or import an approved provider result from Evidence.</p>}
        {visible.map(proposal => <article aria-label={`Proposal ${proposal.assertionId}`} key={proposal.assertionId} className="space-y-2 border border-[var(--console-line)] p-3">
          <div className="flex flex-wrap items-center gap-2">{proposal.reviewState === "proposed" && <input type="checkbox" aria-label={`Select ${proposal.assertionId}`} checked={selected.includes(proposal.assertionId)} onChange={event => setSelected(ids => event.target.checked ? [...ids, proposal.assertionId] : ids.filter(id => id !== proposal.assertionId))} />}<strong>{proposal.kind} · {proposal.predicate}: {displayValue(proposal.value, workspace.proposals, workspace.entities, workspace.bindings)}</strong><span>{proposal.reviewState}</span></div>
          <p className="text-sm">{proposal.subjectEntityId ? workspace.entities.find(e => e.entityId === proposal.subjectEntityId)?.canonicalLabel : proposal.subjectMentionId ? "Subject identity unresolved" : ""} · {proposal.provenance.kind}{proposal.modelScore !== undefined ? ` · Model score ${proposal.modelScore}` : ""}</p>
          {proposal.evidence.map((citation, index) => <Citation key={index} citation={citation} />)}
          {proposal.participants?.length ? <p>Participants: {proposal.participants.map(participant => `${participant.role}: ${displayValue({ type: "entity", mentionId: participant.mentionId }, workspace.proposals, workspace.entities, workspace.bindings)}`).join("; ")}</p> : null}{proposal.attributes?.map((attribute, index) => <p key={index}>{attribute.predicate}: {displayValue(attribute.value, workspace.proposals, workspace.entities, workspace.bindings)}</p>)}{proposal.occurredTime && <p>Occurred: {proposal.occurredTime.start}{proposal.occurredTime.end ? ` to ${proposal.occurredTime.end}` : ""}{proposal.occurredTime.uncertain ? " (uncertain)" : ""}</p>}
          <p className="text-xs">Cases: {caseNames(workspace.memberships.filter(m => m.included && ((m.targetKind === "knowledge" && m.targetId === proposal.assertionId) || (m.targetKind === "evidence" && proposal.evidence.some(ref => ref.evidenceId === m.targetId)))).map(m => m.caseId).filter((id, index, ids) => ids.indexOf(id) === index))}</p>
          <div className="flex flex-wrap gap-2"><button className={button} onClick={() => setInspectId(proposal.assertionId)}>Sources and history {proposal.assertionId}</button><button className={button} onClick={() => { setEdit(proposal); document.getElementById("knowledge-composer")?.scrollIntoView({ block: "start" }); }}>Edit as new proposal</button>{proposal.reviewState === "proposed" && <><button className={button} disabled={!rationale.trim()} onClick={() => void review([proposal.assertionId], "accept")}>Accept</button><button className={button} disabled={!rationale.trim()} onClick={() => void review([proposal.assertionId], "reject")}>Reject</button></>}{proposal.reviewState === "accepted" && <button className={button} disabled={!rationale.trim()} onClick={() => void review([proposal.assertionId], "withdraw")}>Withdraw</button>}<button className={button} disabled={!rationale.trim()} onClick={() => void review([proposal.assertionId], "dispute")}>Preserve dispute</button></div>
        </article>)}
      </section>
      {inspected && <section aria-label="Selected knowledge sources and history" className={box}>
        <h3 className="font-semibold">{inspected.predicate}: {displayValue(inspected.value, workspace.proposals, workspace.entities, workspace.bindings)}</h3><p className="break-all">{inspected.assertionId} · Schema {inspected.schemaId} · Proposal {inspected.proposalEventId}</p>
        {inspected.evidence.map((citation, index) => <Citation key={index} citation={citation} />)}
        <p>Origin: {inspected.provenance.kind}{inspected.provenance.provider ? ` · ${inspected.provenance.provider} · ${inspected.provenance.model} · ${inspected.provenance.promptVersion} · ${inspected.provenance.invocationId}` : ""}</p>
        {inspected.derivedFrom && <p>Edited from {inspected.derivedFrom}; the original remains in history.</p>}
        <ol>{workspace.bindingHistory.filter(entry => entry.mentionId === inspected.mentionId).map(entry => <li key={entry.eventId} className="my-2 break-words">{entry.occurredAt} · {entry.actorId} · Binding {entry.previousEntityId ?? "unbound"} → {entry.entityId}: {entry.rationale}</li>)}{inspected.history.map(entry => <li key={entry.eventId} className="my-2 break-words">{entry.occurredAt} · {entry.actorId} · {entry.action}: {entry.rationale}{entry.replacementId ? ` · Replacement ${entry.replacementId}` : ""}</li>)}</ol>
        {workspace.cases.map(item => <label key={item.caseId} className="flex gap-2"><input type="checkbox" checked={workspace.memberships.some(m => m.included && m.targetKind === "knowledge" && m.targetId === inspected.assertionId && m.caseId === item.caseId)} onChange={event => void decide({ action: "membership", caseId: item.caseId, targetKind: "knowledge", targetId: inspected.assertionId, included: event.target.checked })} />Knowledge membership in {item.title}</label>)}
        {inspected.reviewState === "accepted" && <form className="space-y-2" onSubmit={event => { event.preventDefault(); const replacementId = new FormData(event.currentTarget).get("replacementId"); const replacement = workspace.proposals.find(p => p.assertionId === replacementId); const priorBinding = workspace.bindings.find(b => b.mentionId === inspected.mentionId); void decide({ action: "review", reviews: [...(replacement?.reviewState === "proposed" ? [{ assertionId: replacement.assertionId, proposalEventId: replacement.proposalEventId, action: "accept", rationale, ...(replacement.kind === "entity" && replacement.mentionId === inspected.mentionId && priorBinding ? { entityId: priorBinding.entityId } : {}) }] : []), { assertionId: inspected.assertionId, proposalEventId: inspected.proposalEventId, action: "supersede", replacementId, rationale }] }); }}><label className="flex flex-col gap-1">Correction replacement<select name="replacementId" className={field} required><option value="">Choose a replacement (proposals accepted atomically)</option>{workspace.proposals.filter(p => p.assertionId !== inspected.assertionId && ["proposed", "accepted"].includes(p.reviewState)).map(p => <option key={p.assertionId} value={p.assertionId}>{p.predicate}: {displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)} · {p.assertionId}</option>)}</select></label><button className={button} disabled={!rationale.trim()}>Supersede with correction</button></form>}
        {inspected.kind === "entity" && inspected.mentionId && inspected.reviewState === "accepted" && <BindingForm proposal={inspected} workspace={workspace} rationale={rationale} decide={decide} />}
      </section>}
      <section aria-label="Relationships and occurrences" className={box}>
        <h3 className="font-semibold">Relationships</h3><label className="flex flex-col gap-1">Relationship filter<select className={field} value={relationshipFilter} onChange={event => setRelationshipFilter(event.target.value)}><option value="">All relationship types</option>{(workspace.schema ?? investigationVocabulary).predicates.filter(p => p.kind === "relationship").map(p => <option key={p.name}>{p.name}</option>)}</select></label>
        <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Subject</th><th>Relationship</th><th>Object</th><th>Review</th></tr></thead><tbody>{relationships.map(p => <tr key={p.assertionId}><td>{workspace.entities.find(e => e.entityId === p.subjectEntityId)?.canonicalLabel ?? "Unresolved"}</td><td>{p.predicate}</td><td>{displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)}</td><td><button className={button} onClick={() => setInspectId(p.assertionId)}>Inspect {p.assertionId}</button></td></tr>)}</tbody></table></div>
        {dossier && <><h4 className="font-semibold">One-step neighborhood of {dossier.canonicalLabel}</h4><p>At most 20 current relationships; use the relationship filter to narrow this view.</p><ul>{relationships.slice(0, 20).map(p => <li key={p.assertionId}>{workspace.entities.find(e => e.entityId === p.subjectEntityId)?.canonicalLabel ?? "Unresolved"} → {p.predicate} → {displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)}</li>)}</ul></>}
        <h3 className="font-semibold">Real-world occurrences</h3><p>Occurrence dates below are separate from publication, discovery and ingestion dates. Multiple assertions may describe the same occurrence. Identity across sources remains unresolved until you review and select a shared occurrence identity. These groups are not independent event totals.</p>{[...new Set(occurrences.map(p => p.occurrenceId))].map(id => { const group = occurrences.filter(p => p.occurrenceId === id); return <article key={id} className="space-y-2 border p-2"><p>{id} · {group.length} supporting assertions</p>{group.map(p => <button key={p.assertionId} className={button} onClick={() => setInspectId(p.assertionId)}>{p.predicate}: {displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)} · Occurred {p.occurredTime?.start ?? "unknown"}{p.occurredTime?.uncertain ? " (uncertain)" : ""} · Published {p.publicationTime?.start ?? "unknown"}</button>)}</article>; })}
      </section>
      <LineageForm workspace={workspace} sources={sources} decide={decide} />
    </fieldset>
  </section>;
}

function Citation({ citation }: { citation: KnowledgeCitation }) {
  return <blockquote className="space-y-1 border-l-2 border-[var(--console-line-strong)] pl-3"><p className="whitespace-pre-wrap break-words">{citation.quote}</p><a className="underline" href={`#evidence/${citation.evidenceId}/${citation.extractionId}/${citation.passageIndex}`}>Open source passage · {locatorLabel(citation.locator)}</a>{citation.pdfCoverage && <PdfCoverageNotice coverage={citation.pdfCoverage} />}</blockquote>;
}

function BindingForm({ proposal, workspace, rationale, decide }: { proposal: ReviewProposal; workspace: SharedKnowledge; rationale: string; decide: (body: Record<string, unknown>) => Promise<void> }) {
  const binding = workspace.bindings.find(item => item.mentionId === proposal.mentionId);
  const matches = suggestEntityMatches(proposal, workspace);
  return <form aria-label="Correct source identity binding" className="space-y-2 border p-3" onSubmit={event => { event.preventDefault(); const value = new FormData(event.currentTarget).get("entityId") as string; void decide({ action: "bind", mentionId: proposal.mentionId, assertionId: proposal.assertionId, entityId: value === "new" ? newKnowledgeId("ent") : value, previousEntityId: binding?.entityId ?? null, rationale }); }}><h4 className="font-semibold">Bind or repair this source mention</h4><p>Current identity: {workspace.entities.find(e => e.entityId === binding?.entityId)?.canonicalLabel ?? "Unbound"} ({binding?.entityId ?? "none"}). Similar names never merge automatically. Use source identifiers and attributes to verify identity.</p>{matches.length > 0 && <section aria-label="Possible identity matches"><h5>Possible matches to review</h5><ul>{matches.map(match => <li key={match.entity.entityId}>{match.entity.canonicalLabel} · {match.entity.entityId}: {match.reasons.join("; ")}</li>)}</ul><p>Inspect their dossiers and sources before choosing. These suggestions make no identity decision.</p></section>}<label className="flex flex-col gap-1">Verified entity identity<select name="entityId" className={field} required><option value="">Choose explicitly</option><option value="new">Create a distinct identity</option>{workspace.entities.filter(e => e.entityType === proposal.entityType).map(entity => <option key={entity.entityId} value={entity.entityId}>{entity.canonicalLabel} · {entity.entityId} · {entity.evidenceIds.length} sources</option>)}</select></label><button className={button} disabled={!rationale.trim()}>Save identity binding or repair</button></form>;
}

function LineageForm({ workspace, sources, decide }: { workspace: SharedKnowledge; sources: SourceItem[]; decide: (body: Record<string, unknown>) => Promise<void> }) {
  const [evidenceId, setEvidenceId] = useState("");
  const lineage = workspace.lineage?.find(item => item.evidenceId === evidenceId);
  return <section aria-label="Source independence review" className={box}><h3 className="font-semibold">Source lineage and independence</h3><p>Copies and reports quoting the same origin are not independent corroboration. Leave independence unknown unless you have reviewed the origin.</p><form className="space-y-2" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); void decide({ action: "lineage", evidenceId, originId: data.get("originId") || evidenceId, independence: data.get("independence"), rationale: data.get("rationale") }); }}>
    <label className="flex flex-col gap-1">Source to review<select className={field} value={evidenceId} onChange={event => setEvidenceId(event.target.value)} required><option value="">Choose a source</option>{sources.map(item => <option key={item.evidenceId} value={item.evidenceId}>{sourceLabel(item)}</option>)}</select></label>
    <p>Current: {lineage?.independence ?? "unknown"} · Origin {lineage?.originId ?? "unresolved"}{lineage ? ` · ${lineage.rationale}` : ""}</p>
    <label className="flex flex-col gap-1">Independence decision<select name="independence" className={field}><option value="unknown">Unknown</option><option value="independent">Reviewed independent origin</option><option value="derived">Derived from another source</option></select></label>
    <label className="flex flex-col gap-1">Shared origin<select name="originId" className={field}><option value="">This source is its own origin</option>{sources.map(item => <option key={item.evidenceId} value={item.evidenceId}>{sourceLabel(item)}</option>)}</select></label>
    <label className="flex flex-col gap-1">Source independence rationale<textarea name="rationale" className={field} required /></label><button className={button} disabled={!evidenceId}>Record source lineage</button>
  </form></section>;
}

function ProposalComposer({ workspace, sources, edit, onCancel, onPropose }: { workspace: SharedKnowledge; sources: SourceItem[]; edit: ReviewProposal | undefined; onCancel: () => void; onPropose: (proposals: KnowledgeProposal[]) => Promise<void> }) {
  const schema = workspace.schema ?? investigationVocabulary;
  const [participants, setParticipants] = useState(edit?.participants?.length ? edit.participants : [{ role: "participant", mentionId: "" }]);
  const [attributes, setAttributes] = useState(edit?.attributes ?? []);
  const [kind, setKind] = useState<KnowledgeProposal["kind"]>(edit?.kind ?? "entity");
  const [predicate, setPredicate] = useState(edit?.predicate ?? "name");
  const [value, setValue] = useState(edit?.value.type === "entity" ? edit.value.mentionId : edit ? String(edit.value.value) : "");
  const [sourceId, setSourceId] = useState("");
  const [content, setContent] = useState<SourceContent>();
  const [passageIndex, setPassageIndex] = useState(0);
  const [quote, setQuote] = useState("");
  const [evidence, setEvidence] = useState<KnowledgeCitation[]>(edit?.evidence ?? []);
  const [error, setError] = useState<string>();
  useEffect(() => { let canceled = false; setContent(undefined); setQuote(""); setPassageIndex(0); if (sourceId) void knowledgeRequest<SourceContent>(`/api/evidence/${encodeURIComponent(sourceId)}/content`).then(data => { if (!canceled) { setContent(data); setQuote(data.citations?.[0]?.quote ?? ""); } }).catch(reason => { if (!canceled) setError(String(reason)); }); return () => { canceled = true; }; }, [sourceId]);
  const selectedPredicate = schema.predicates.find(item => item.name === predicate && item.kind === kind);
  const mentions = workspace.proposals.filter(item => item.kind === "entity" && (item.reviewState === "accepted" || item.reviewState === "proposed"));
  return <section id="knowledge-composer" aria-label="Manual knowledge proposal" className={box}>
    <h3 className="font-semibold">{edit ? `Edit ${edit.assertionId} as a new proposal` : "Propose knowledge from a source"}</h3><p>Create entities first, then reference their source mentions in facts, relationships and occurrences. Review can keep a new entity distinct or explicitly bind it to a verified existing identity.</p>
    {error && <p role="alert">{error}</p>}
    <div className="space-y-2"><label className="flex flex-col gap-1">Supporting source<select className={field} value={sourceId} onChange={event => setSourceId(event.target.value)}><option value="">Choose an imported source</option>{sources.map(item => <option key={item.evidenceId} value={item.evidenceId}>{sourceLabel(item)}</option>)}</select></label>
      {content && !content.extraction && <p>No extracted passages available. Run extraction in Ingestion first.</p>}
      {content?.extraction && <><label className="flex flex-col gap-1">Supporting passage<select className={field} value={passageIndex} onChange={event => { const index = Number(event.target.value); setPassageIndex(index); setQuote(content.citations[index]?.quote ?? ""); }}>{content.extraction.passages.map((passage, index) => <option key={index} value={index}>{index + 1}: {locatorLabel(passage.locator)} · {passage.text.slice(0, 90)}</option>)}</select></label><p className="whitespace-pre-wrap break-words">{content.extraction.passages[passageIndex]?.text}</p>{content.extraction.format === "pdf" && <PdfCoverageNotice coverage={content.extraction.pdfCoverage ?? { status: "unknown" }} />}<label className="flex flex-col gap-1">Exact supporting quote<textarea className={field} value={quote} onChange={event => setQuote(event.target.value)} /></label><button type="button" className={button} disabled={!quote.trim() || !content.citations[passageIndex] || evidence.length >= 24} onClick={() => { const citation = content.citations[passageIndex]; if (citation) setEvidence(items => [...items, { ...citation, quote }]); }}>Add supporting passage</button></>}
      <p>{evidence.length} supporting passages selected. Add several sources when they support this same value.</p>{evidence.map((citation, index) => <div key={index}><Citation citation={citation} /><button className={button} onClick={() => setEvidence(items => items.filter((_, i) => i !== index))}>Remove supporting passage {index + 1}</button></div>)}
    </div>
    <form aria-label="Propose knowledge" className="space-y-3" onSubmit={event => {
      event.preventDefault(); setError(undefined); const data = new FormData(event.currentTarget);
      if (!selectedPredicate) { setError("Choose a reviewed predicate."); return; }
      const typedValue: KnowledgeValue = selectedPredicate.valueType === "entity" ? { type: "entity", mentionId: value } : selectedPredicate.valueType === "number" ? { type: "number", value: Number(value), ...(data.get("unit") ? { unit: String(data.get("unit")) } : {}) } : selectedPredicate.valueType === "boolean" ? { type: "boolean", value: value === "true" } : { type: selectedPredicate.valueType, value };
      const start = String(data.get("occurredStart") ?? ""); const end = String(data.get("occurredEnd") ?? ""); const publication = String(data.get("publication") ?? "");
      const proposal: KnowledgeProposal = { assertionId: newKnowledgeId("as"), workspaceId: workspace.workspaceId, schemaId: schema.schemaId, kind, predicate, value: typedValue, evidence, provenance: { kind: "manual" }, ...(edit ? { derivedFrom: edit.assertionId } : {}), ...(kind === "entity" ? { mentionId: edit?.mentionId ?? newKnowledgeId("mention"), entityType: String(data.get("entityType")) } : {}), ...((kind === "fact" || kind === "relationship") ? { subjectMentionId: String(data.get("subject")) } : {}), ...(kind === "occurrence" ? { occurrenceId: String(data.get("occurrenceId")) || newKnowledgeId("occurrence"), participants, attributes, ...(start ? { occurredTime: { start, ...(end ? { end } : {}), uncertain: data.get("uncertain") === "on" } } : {}), ...(publication ? { publicationTime: { start: publication, uncertain: data.get("publicationUncertain") === "on" } } : {}) } : {}) };
      void onPropose([proposal]);
    }}>
      <div className="grid gap-3 md:grid-cols-2"><label className="flex flex-col gap-1">Knowledge kind<select className={field} value={kind} onChange={event => { const next = event.target.value as KnowledgeProposal["kind"]; setKind(next); setPredicate(schema.predicates.find(p => p.kind === next)!.name); setValue(""); }}><option value="entity">Entity mention</option><option value="fact">Typed fact</option><option value="relationship">Relationship</option><option value="occurrence">Real-world occurrence</option></select></label><label className="flex flex-col gap-1">Predicate<select className={field} value={predicate} onChange={event => { setPredicate(event.target.value); setValue(""); }}>{schema.predicates.filter(item => item.kind === kind).map(item => <option key={item.name}>{item.name}</option>)}</select></label></div>
      {kind === "entity" && <label className="flex flex-col gap-1">Entity type<select className={field} name="entityType" defaultValue={edit?.entityType ?? "person"}>{schema.entityTypes.map(type => <option key={type}>{type}</option>)}</select></label>}
      {(kind === "fact" || kind === "relationship") && <label className="flex flex-col gap-1">Subject source mention<select className={field} name="subject" defaultValue={edit?.subjectMentionId ?? ""} required><option value="">Choose source mention</option>{mentions.map(item => <option key={item.assertionId} value={item.mentionId}>{displayValue(item.value)} · {item.mentionId} · {item.reviewState}</option>)}</select></label>}
      <label className="flex flex-col gap-1">Proposed value{selectedPredicate?.valueType === "entity" ? <select className={field} value={value} onChange={event => setValue(event.target.value)} required><option value="">Choose related source mention</option>{mentions.map(item => <option key={item.assertionId} value={item.mentionId}>{displayValue(item.value)} · {item.mentionId}</option>)}</select> : <input className={field} required value={value} onChange={event => setValue(event.target.value)} type={selectedPredicate?.valueType === "number" ? "number" : "text"} step="any" placeholder={selectedPredicate?.valueType === "date" ? "YYYY, YYYY-MM, or YYYY-MM-DD" : "Value supported by selected quotations"} />}</label>
      {selectedPredicate?.valueType === "number" && <label className="flex flex-col gap-1">Unit (optional)<input className={field} name="unit" defaultValue={edit?.value.type === "number" ? edit.value.unit : ""} placeholder="USD" /></label>}
      {kind === "occurrence" && <><label className="flex flex-col gap-1">Occurrence identity<select className={field} name="occurrenceId" defaultValue={edit?.occurrenceId ?? ""}><option value="">Create an occurrence identity (cross-source match unresolved)</option>{workspace.proposals.filter(p => p.kind === "occurrence").filter((p, index, items) => items.findIndex(other => other.occurrenceId === p.occurrenceId) === index).map(p => <option key={p.occurrenceId} value={p.occurrenceId}>{displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)} · {p.occurrenceId}</option>)}</select></label>{participants.map((participant, index) => <div key={index} className="space-y-2"><label className="flex flex-col gap-1">Occurrence participant {index + 1}<select className={field} value={participant.mentionId} onChange={event => setParticipants(items => items.map((item, i) => i === index ? { ...item, mentionId: event.target.value } : item))} required><option value="">Choose participant mention</option>{mentions.map(p => <option key={p.assertionId} value={p.mentionId}>{displayValue(p.value, workspace.proposals, workspace.entities, workspace.bindings)} · {p.mentionId}</option>)}</select></label><label className="flex flex-col gap-1">Participant role {index + 1}<input className={field} value={participant.role} onChange={event => setParticipants(items => items.map((item, i) => i === index ? { ...item, role: event.target.value } : item))} required /></label>{participants.length > 1 && <button type="button" className={button} onClick={() => setParticipants(items => items.filter((_, i) => i !== index))}>Remove participant {index + 1}</button>}</div>)}<button type="button" className={button} disabled={participants.length >= 20} onClick={() => setParticipants(items => [...items, { role: "participant", mentionId: "" }])}>Add occurrence participant</button>
      {attributes.map((attribute, index) => <div key={index} className="space-y-2"><label className="flex flex-col gap-1">Occurrence attribute {index + 1}<select className={field} value={attribute.predicate} onChange={event => { const name = event.target.value; const type = schema.predicates.find(p => p.name === name && p.kind === "fact")!.valueType; setAttributes(items => items.map((item, i) => i === index ? { predicate: name, value: type === "number" ? { type: "number", value: 0 } : { type: type === "date" ? "date" : "string", value: "" } } : item)); }}>{schema.predicates.filter(p => p.kind === "fact").map(p => <option key={p.name}>{p.name}</option>)}</select></label><label className="flex flex-col gap-1">Occurrence attribute value {index + 1}<input className={field} value={displayValue(attribute.value)} required onChange={event => { const raw = event.target.value; const type = schema.predicates.find(p => p.name === attribute.predicate && p.kind === "fact")!.valueType; setAttributes(items => items.map((item, i) => i === index ? { ...item, value: type === "number" ? { type: "number", value: Number(raw) } : { type: type === "date" ? "date" : "string", value: raw } } : item)); }} /></label><button type="button" className={button} onClick={() => setAttributes(items => items.filter((_, i) => i !== index))}>Remove attribute {index + 1}</button></div>)}<button type="button" className={button} disabled={attributes.length >= 20} onClick={() => setAttributes(items => [...items, { predicate: "description", value: { type: "string", value: "" } }])}>Add occurrence attribute</button><label className="flex flex-col gap-1">Occurrence date or interval start<input className={field} name="occurredStart" defaultValue={edit?.occurredTime?.start ?? ""} placeholder="YYYY, YYYY-MM, or YYYY-MM-DD; blank if unknown" /></label><label className="flex flex-col gap-1">Occurrence interval end<input className={field} name="occurredEnd" defaultValue={edit?.occurredTime?.end ?? ""} /></label><label className="flex gap-2"><input type="checkbox" name="uncertain" defaultChecked={edit?.occurredTime?.uncertain ?? false} />Occurrence time is uncertain</label><label className="flex flex-col gap-1">Publication date (separate, optional)<input className={field} name="publication" defaultValue={edit?.publicationTime?.start ?? ""} placeholder="YYYY, YYYY-MM, or YYYY-MM-DD" /></label><label className="flex gap-2"><input type="checkbox" name="publicationUncertain" defaultChecked={edit?.publicationTime?.uncertain ?? false} />Publication date is uncertain</label></>}
      <button className={button} disabled={!evidence.length}>Save unreviewed proposal</button>{edit && <button type="button" className={button} onClick={onCancel}>Return to new proposal</button>}
    </form>
  </section>;
}
